- name: Create Azure Container Registry to modernize TODO Application
  hosts: localhost
  connection: local
  vars_files:
    - ./vars-myvars.yml

  tasks:

    - name: Create an Azure Container Registry for TODO Application
      azure_rm_containerregistry:
        name: "{{ vm_name }}{{ rnum }}acr"
        resource_group: "{{ resource_group }}"
        admin_user_enabled: true
        sku: Premium
        tags:
            Release: Initial
            Environment: RedHatSummit
      register: acr_output

    - name: Getting ACR Username
      set_fact:
        acrusername: "{{ acr_output.name }}"

    - name: Getting ACR Password
      set_fact:
        acrpassword: "{{ acr_output.credentials.password }}"

    - name: Getting ACR Host
      set_fact:
        acrhostname: "{{ acr_output.login_server }}"

    - debug:
        msg: "ACR Username: {{ acrusername }}"

    - debug:
        msg: "ACR Password: {{ acrpassword }}"

    - debug:
        msg: "ACR Hostname: {{ acrhostname }}"

